apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:1ESoZeOvBmNxCEUaTGMrpTlHg6iRlLMyx3omP17WLBYC0RiajgDrvg==,iv:CbzLJGdqyH7F0JAAOlIaYBQ/k+yhJMA1C5Ae/mD7prE=,tag:YFZWOkotTGyF5tNxwGpccA==,type:str]
sops:
  age:
    - recipient: age1w69hxskvxje87wnzvwrkvkl6re2vm27zts905jnzr5g78a05m47q94ejzx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaXpUQkhSTnRFTExxVXNB
        TXB2VFl0ektQdFhRNkQ3dmxhVUtneGFoY2pZCk5Gd2M0Y0p5bXcyOHBkSjQ0K3Vr
        SGlXTUpPNUZmTy9GQitGVytkSml0aFUKLS0tIDVabDBEVjBOSmo4dGMrbVJuMnZU
        Q29Sc051L3Nlam1LQVU4c2hxcm9oUm8KybUW5Zz4cHJpEKTXFiIym+Vwy4/wSsSv
        PZBZi/aN/mBbulBfjZqYmaTJyBXvJPPAR27qsvu3XyZSQbQbgWM3YQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T22:59:50Z"
  mac: ENC[AES256_GCM,data:uhdr0h9F4rro3c64c137NaW8bG9peHkxd9JJ0ttVpIuWmFItgfUjlRxGVye0V8V8MDV5IOEshNQafgPD5dYD/INMej+RToDV6pZ7Z9nsxng/xFkxKHpje2E9QeiiCsEIg5hEX8WJwW17NjzL8SU3dHqWpcvlHxj3CtTubT3g3Wg=,iv:YFodCadc0bDXXOua9BfWQHO3KWbw8v9C4OxeSLywjrU=,tag:8lbhkXAgDJ/z0PXAIWnj3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
