apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:K8+oa6Vi+p5226x3ESf4bVQ4BJ062zJ6Ci93SJT660F2KhKEKvt+s3M7rS6mpumseh7hXzGnyuNaPkOahA6P//WXNzLFNLZ7KUi6,iv:SBGNBJMasCsRhgOVd4jGxnPewguu0KoVnk33M6yrxCk=,tag:Rbcu8DnrOkKkkVeNuz/rLg==,type:str]
sops:
  age:
    - recipient: age1w69hxskvxje87wnzvwrkvkl6re2vm27zts905jnzr5g78a05m47q94ejzx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5azlHN280TlNvYWZWaDNr
        U1R6YzdCTmRaRDNaRjBuUGU0eGVydXMwb2tNCktNUjFES2EreUlBWWNqd3JPcExY
        OURwUzBoNXJMY0pBcWRNV1ZqT2paaUEKLS0tIG1xUFB5WDhteGhhY1RkQ1JHQXcz
        NGYxZ3pYNnJ1am1hQ3gzOGFCS2V5TkEKKuTCs4O7N/YwhnOPWpgsL8Iz0vq73zj3
        ar0tXBuUb7VXKf++aX69z/Ae13YP4kQUCjac6WaIDXqn2WheYIOHeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T22:59:50Z"
  mac: ENC[AES256_GCM,data:bc8pLLd9Jlen/N1oPxzYGlQeQ9uLaAuSQRP4nIgrqDoNVyiScIBlCU0LP5l8sZZkI5aHPWkeyRrgKawvjvg9Xwcs0LIVF/ILZwdRRFtQFrmPfeZLo8MmAGBgRnWkoB7YYla9XfvdNoYnKU0ZLi2u4BFkBjRiWmunNoSJCWrckAU=,iv:6bH+oZbmdwBqzF51GoB0mMSpVHjpjjBo9kGfGEGAgLY=,tag:Qx2yqSB3D1Te/XYNxreKPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
