apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.moonsuit.org
      recordType: CNAME
      targets:
        - db6490b2-2898-4388-a56f-46c645048ef6.cfargotunnel.com
sops:
  age:
    - recipient: age1w69hxskvxje87wnzvwrkvkl6re2vm27zts905jnzr5g78a05m47q94ejzx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbGM3MmFrZUJzZUZTU0k4
        TWFjcHZYRmpLRlNvYWhjcFVOR1JMRDAwMm1FCmRxTEU2TVdrNXpDREM4OEFUZzhi
        UWdnKzdzcUQzZGx1Q2w3bHY0Zkd6eDgKLS0tIGMrcjlHU1l1SzNKb0E5K1B6ajBU
        Tk4zYjNVWU93RUtXNk1SMkRIZjdvck0K1WuSRBvgU25KpB9FWKqebEMb3OyIWbxc
        exSHvC1hgZegLIB2QoiqchF7Fhvh49b7lKtw0V2DAOofQbW9jWxA2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T22:59:50Z"
  mac: ENC[AES256_GCM,data:1uOb7/RnDEuOQSXmspx8oocEiriAZ1u9w149m5ahbI14hmrKQfpLlt90BZZmzHR10hsgql1hSBLXJT/r+OppAbPoZ4JTfS81mia89/swgDVn0TzA0GDaPrR/Wfz3ZMvDUF+RWvFfkNHy/juDYsxoo0o4OHZyxMaHhWN38qW1OC0=,iv:NUQKU2Zza0aftyWXXgXLANEaDHX7SdnXL8RpTtpBR6U=,tag:wwGQMWwlpBK5VSH6ii/ZnA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
