apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:MrGPhugqgkOTZ19IPzy9Kz8gCE/7naTIOqdwgg2xlWGDgkG/w4H17gYfI5g9vEYSUAphbaTvs1VjSTdAlAWpljkcso1nowioe6yqJ1w0SXEeZdY7olZbVU6K2TeXQaYFva2wz8BWvJ3vL/4KXQyZGcusnDzzsFidIwaeY7OyJH1PUQfk2V31ydE4le9qnuxmCtbFTrJiJAlfsTGSRADsl6kh+fVbX61twwYs52J5gmQi5uZL,iv:xHaANBJOWrsvcNtuASY78mB354s4yjy35/NRnlXne58=,tag:+bBeTaHqeGcSvpTbbFv+xQ==,type:str]
sops:
  age:
    - recipient: age1w69hxskvxje87wnzvwrkvkl6re2vm27zts905jnzr5g78a05m47q94ejzx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2R04wRFNWQkdidHdpNFhy
        Y1ZRb2FPTUlGVmxnUDFDWVFmZW9adFJoNEE0CjJNM2R0MGN4UHFheEhLS1VTRi9S
        dEFYNXdsVXdNbk1ncmFUUkZLSkVXU00KLS0tIDBwVkdXdUZCNEZhcFk0L010akpC
        MTJXSmxUa2pOejNVZFlQU3NLbnVlNmcKBRBE6lp9F4oHGAg2Lkt5t0EPXoz2yVod
        Tkrt5U4pc6Ktu/ZY0I3YW5NZ9j/i1HRT4C6iukILWRzgm08DM4ZewA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T22:59:50Z"
  mac: ENC[AES256_GCM,data:Ci1kEDIq8tdrOGRqUVuAJREQV9ipsBp86b+nfVnhlAfEwiNQA/7iBAlWIheMytd+IZSlO+9wMI90UP6kdfeeT+1LrGBHJ06iio83757dpxc49h3lMWFoxVGpghzQtym4eiRzdWTfCwKyqJ0ohONGYX59yW5+0ovOtyduNwZBX7U=,iv:YCtd6gUEq7rNmW5s09vy95+rxG+D5pTdeGkoyENLRhQ=,tag:KMVKafhOL0VDhvOWT3+BVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
