apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:QGxa2zPivYUkYaiRYDrcIX+9MDlQIgyptnMxZv0dmN31Vxw8xHvaTA==,iv:cpGp8b6NNzuE/uxrz1IvBSJj8wnvaiPBjSEtn1CCr0c=,tag:VN7IHp7e/cuoRGkdbYtHtA==,type:str]
sops:
  age:
    - recipient: age1w69hxskvxje87wnzvwrkvkl6re2vm27zts905jnzr5g78a05m47q94ejzx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RUlEZ01NeTU3T1RVaXJL
        Ym9YVlRzbUp5WURkbHQ3N1kxWUNLS2Nzd1JrCkM0K1FUOGYxekRmYU96YktTSnBR
        QXE5T2NJdTRqN0MxN3JBUDFiSlM5bk0KLS0tIDNLZnhXZG5yUFJCWGtWa1p3V3NU
        aloyTTBTR0Rmdno1NHpRRTRuYTZkZ2MK5Vp/N/jAxySPlxdrlquBIjxHhIe1B/uI
        9N0B+zsZwCVa5/uVr7N/lr6MWViCA3VN63Rp0IAhzd74JPMFIypN4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T22:59:50Z"
  mac: ENC[AES256_GCM,data:JanVshCihOx6xZTCHdFKDuss51C9hGxMN00RQwJVPLHBbJl/SldRYXg/jFqx7nqZFlWQ8cgx4Gb6mXidkj/iDWE288KtjIcdWqkmshA1dX8xL1j0zVuJZa+JPcNtbhwiEZ9cqjcC469uwV+U0xc9VNftoCxdz1q8AVrxsAE4ENQ=,iv:uPZCA0/wp1//hw+EusfXudSOWGy7fZd1DhXiPNxeKKM=,tag:q/PWfm1Ey+3GihDPooTk1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
